-- The SQL Statements should be delimted by semicolon.

CREATE  INDEX L_SHIPDATE_CLUIDX ON LINEITEM(L_SHIPDATE) ;

CREATE INDEX L_ORDERKEY_IDX ON LINEITEM(L_ORDERKEY) ;

CREATE INDEX N_REGIONKEY_IDX ON NATION(N_REGIONKEY) ;

CREATE  INDEX O_ORDERDATE_CLUIDX ON ORDERS(O_ORDERDATE) ;

CREATE INDEX S_NATIONKEY_IDX ON SUPPLIER(S_NATIONKEY) ;

CREATE INDEX PS_SUPPKEY_IDX ON PARTSUPP(PS_SUPPKEY) ;

CREATE INDEX L_PARTKEY_IDX ON LINEITEM(L_PARTKEY) ;

ALTER TABLE NATION ADD CONSTRAINT PK_N_NATIONKEY PRIMARY KEY (N_NATIONKEY) ; 
 
ALTER TABLE REGION ADD CONSTRAINT PK_R_REGIONKEY PRIMARY KEY (R_REGIONKEY) ;

ALTER TABLE PART ADD CONSTRAINT PK_P_PARTKEY PRIMARY KEY (P_PARTKEY) ;

ALTER TABLE SUPPLIER ADD CONSTRAINT PK_S_SUPPKEY PRIMARY KEY (S_SUPPKEY) ;

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_C_CUSTKEY PRIMARY KEY (C_CUSTKEY) ;

ALTER TABLE PARTSUPP ADD CONSTRAINT PK_PS_PARTKEY_PS_SUPPKEY PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY) ;

ALTER TABLE ORDERS ADD CONSTRAINT PK_O_ORDERKEY PRIMARY KEY (O_ORDERKEY) ;

