DROP TABLE IF EXISTS CUSTOMER ; 

DROP TABLE IF EXISTS LINEITEM ; 

DROP TABLE IF EXISTS NATION ; 

DROP TABLE IF EXISTS ORDERS ; 

DROP TABLE IF EXISTS PART ; 

DROP TABLE IF EXISTS PARTSUPP ; 

DROP TABLE IF EXISTS REGION ; 

DROP TABLE IF EXISTS SUPPLIER ; 

